### ISSUE TITLE
gpu memory 집계 및 인덱스 표기 에러 

### ISSUE THREAD

**Issue by velpegor** [Haawron/SLURM_allocated_gres_visualizer#10]
[issue 01]

현재 서버에 gpu01, gpu03이라는 노드가 존재하고 각각에 표시된 gpu개수는 잘 나옵니다.
근데 gpu01 노드에 2번 인덱스의 gpu가 할당되어있는데 slurm-gres-viz 에서는 0번 인덱스로 잡혀있는 것으로 표기가 됩니다. 

<img width="563" alt="image" src="https://github.com/Haawron/SLURM_allocated_gres_visualizer/assets/83739271/daaaa4f6-802b-47c7-9c73-286a35ad8faf">

<img width="599" alt="image" src="https://github.com/Haawron/SLURM_allocated_gres_visualizer/assets/83739271/509af90c-1391-48e3-a125-953f66729ce0">

----------------------------------------------------------------------------------------------------------------
[issue 02]
추가적으로 메모리도 잡히질 않는데, 이는 필요한 기능까지는 아니여서 크게 상관없을 듯 합니다.

----------------------------------------------------------------------------------------------------------------
[issue 03]
slurm-gres-viz, slurm-gres-viz -i는 잘 동작하나 slurm-gres-viz -gm -gu,  slurm-gres-viz -f 등 이런 명령어들은 

Traceback (most recent call last):
  File "/usr/local/bin/slurm-gres-viz", line 11, in <module>
    load_entry_point('slurm-gres-viz==2.1.1', 'console_scripts', 'slurm-gres-viz')()
  File "/usr/local/lib/python3.8/dist-packages/slurm_gres_viz-2.1.1-py3.8.egg/slurm_gres_viz/main.py", line 52, in main
  File "/usr/local/lib/python3.8/dist-packages/slurm_gres_viz-2.1.1-py3.8.egg/slurm_gres_viz/main.py", line 31, in wrapper
  File "/usr/local/lib/python3.8/dist-packages/slurm_gres_viz-2.1.1-py3.8.egg/slurm_gres_viz/main.py", line 46, in run
  File "/usr/local/lib/python3.8/dist-packages/slurm_gres_viz-2.1.1-py3.8.egg/slurm_gres_viz/visualizer.py", line 31, in __init__
  File "/usr/local/lib/python3.8/dist-packages/slurm_gres_viz-2.1.1-py3.8.egg/slurm_gres_viz/visualizer.py", line 36, in get_infos
  File "/usr/local/lib/python3.8/dist-packages/slurm_gres_viz-2.1.1-py3.8.egg/slurm_gres_viz/visualizer.py", line 50, in get_node_infos
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.8/dist-packages/slurm_gres_viz-2.1.1-py3.8.egg/slurm_gres_viz/visualizer.py", line 44, in get_node
  File "/usr/local/lib/python3.8/dist-packages/slurm_gres_viz-2.1.1-py3.8.egg/slurm_gres_viz/slurm_objects.py", line 69, in __init__
KeyError: 'gpu03'

이와 같은 에러가 발생합니다. 혹시 해결 방법을 아신다면 답변 주시면 감사하겠습니다!
코드는 깃허브 그대로 사용했습니다.

**Comment by Haawron** [comment]
관심 가져주셔서 감사합니다.

1. 슬럼과 엔비디아 드라이버의 GPU 인덱스 할당 방식이 다릅니다. 슬럼 기반 리소스 모니터링을 위해서 슬럼 방식을 채택했습니다.
2. VRAM 말씀하시는 것 맞을까요? 해당 기능은 [프로메테우스](https://github.com/prometheus/prometheus) 기반 모니터링 툴이 필요합니다. [deepops](https://github.com/NVIDIA/deepops)에서 자동으로 설치해줍니다. 스트리밍 데이터에 GPU 정보들이 적혀있습니다.
3. 2,와 동일합니다. GPU 데이터를 받아오려면 프로메테우스가 필요합니다.

GPU 정보를 받아오는 가장 편한 방법은 모든 노드에 ssh로 nvidia-smi를 쏘는 것인데, 이렇게 하려면 슬럼을 이용하지 않고도 해당 노드에 접속할 수 있는 권한이 필요합니다. 하지만 이 권한을 주면 보안 문제가 생기게 됩니다. 따라서 프로메테우스를 사용하는 게 낫습니다.

**Comment by velpegor** [comment]
답변 주셔서 감사드립니다. 

1. 슬럼과 엔비디아 드라이버의 GPU 인덱스 할당 방식이 다르면 slurm-gres-viz를 통해 몇 번 인덱스의 gpu가 할당 되어있는지는 확인이 불가능한건가요? 질문 드렸던 issue 1과 같이 nvidia-smi를 통해 보면 "기존 서버의 2번 인덱스의 gpu가 할당 되어있다"를 slurm-gres-viz에서 [0][-][-] 가 아닌 [-][-][0]로 표시는 안되는걸까요?

2. 프로메테우스가 디폴트로 설치되어 있다는 걸 확인하였습니다. 프로메테우스는 한번도 건드린 적이 없는데 서버에 맞게 설정 해줘야 하는게 있을까요? node-exporter(port 9100), dcgm-exporter(port 9400)는 깃허브 설명과 동일하게 세팅되어 있습니다.

편리한 기능 개발해주셔서 감사드립니다.

**Comment by Haawron** [comment]
죄송해요 제가 답변을 잘못 드린 것 같습니다. 

1. 컴퓨팅 노드들의 `gres.conf`를
    ```bash
    Autodetect=nvml
    ```
    이렇게 설정해보시겠어요? 나머지 줄 다 주석처리하고 저거 한 줄만 넣으시면 됩니다. 저러면 슬럼이 reconfig 시에 NVML -> nvidia-driver 순으로 호출해서 GPU 정보를 받아오고 인덱스가 동기화 됩니다. DCGM도 드라이버 기반이라 한 번에 다 해결 됩니다.  `scontrol reconfig` 한 번 해주셔야 됩니다.

2. [여기](https://github.com/Haawron/SLURM_allocated_gres_visualizer/blob/da92f81c6996959977d6f2682f1052a2ac881de1/slurm_gres_viz/visualizer.py#L42C14-L42C14)에서 노드들의 IP 정보를 `/etc/hosts`를 통해 받아옵니다. 여기에 IP가 안 써있는 것 같습니다.
    ```text
    gpu01 123.456.789.012
    gpu02 123.456.789.013
    gpu03 123.456.789.014
    ```
    이렇게 셋팅 되어있는지 확인해주시겠어요?

**Comment by velpegor** [comment]
답변 주셔서 감사드립니다! 
1. nvml은 설정되어 있는 상태입니다!

<img width="299" alt="image" src="https://github.com/Haawron/SLURM_allocated_gres_visualizer/assets/83739271/5b0e017b-cc04-4f45-a0dd-beb5abc015d4">

밑에 Name=gpu 줄도 필요가 없을까요?


2. ip도 정상적으로 설정되어있으나

/etc/hosts 파일을 보니, 초기 deepops를 설치할 때 gpu01(마스터 노드), gpu02, gpu03을 컴퓨팅 노드로 설정하고 설치를 진행하였습니다. 하지만 로그인 노드를 지정해주지 않는 탓에 유저들이 접속을 못하게 되어서 gpu02를 slurm.conf에서 컴퓨팅 노드에서 제외하고 지금 slurm을 사용 중에 있습니다. /etc/hosts 파일에는 gpu02가 그대로 설정되어 있어서 gpu03을 못받아온 것 같네요! 감사합니다.

**Comment by Haawron** [comment]
1. 네네 첫 줄 빼고 전부 다 `#`으로 주석처리 해주시면 됩니다.
2. 넵 혹시 또 이상있으면 바로 알려주세요! 리포트 감사드립니다.

**Comment by velpegor** [comment]
답변주셔서 정말 감사드립니다! 큰 도움이 되었습니다.
